### ISSUE TITLE
 field data

### ISSUE THREAD

**Issue by brianteeman** [brianteeman/redirectplugin#6]
```
			->from($db->qn('#__user_profiles'))
			->where($db->qn('user_id') . ' = ' . (int) $userId)
			->where($db->qn('profile_key') . ' = ' . $db->q('profile.consent'));
```
@zero-24 
This code means it is hardcoded to check for a value in the #__user_profiles table

But a custom field plugin like yours will be in the #__fields table

So for my use case, and as we dont really need it on anywhere other than a user registration form I think it would be better to create a plugin with the field instead of just a field. Basically the same as the user_profile plugin but with just one field.

Unless you beat me too it I will do this on Sunday. Then I have to find the docs for how to make a package of plugins

**Comment by zero-24** [comment]
> But a custom field plugin like yours will be in the #__fields table

Yes if this ever get saved anywhere. I have suggested my plugin because you wrote

> Create new custom field to use for the GDPR consent

;)

**Comment by brianteeman** [comment]
Yes thanks for the suggestion and the help but I think I will do it as a user plugin

**Comment by zero-24** [comment]
Sounds like a plan 👍 But i would suggest to include this in this plugin here as they only make sense together and this is already a user plugin 😄

**Comment by brianteeman** [comment]
I wasn't sure if I could combine them or not?

**Comment by zero-24** [comment]
Sure you can do that. You just need to implement the events needed in this plugin and ship the field you created.

**Comment by brianteeman** [comment]
Started to create the single plugin and I intend to submit it to core as a new feature

https://github.com/brianteeman/gdprconsent/blob/master/README.md
